---
# Define the parameters the application can use to reference the resolved configuration
# These parameters are loaded with information by the files, environment and command-line
# sections (if used).  But the parameters defines the parameter, its type, default value and
# validation rules.
- name: environment
  $ref: './auto-code.d/common/types/environments.yaml'
- name: rateLimit.enable
  $ref: './auto-code.d/common/types/rateLimit.enable.default.yaml'
- name: api.protocol
  $ref: './auto-code.d/common/types/protocols-httpContract.yaml'
- name: api.address
  $ref: './auto-code.d/common/types/listen-address-any.yaml'
- name: api.port
  default: 8080
- name: frontend.protocol
  $ref: './auto-code.d/common/types/protocols-httpContract.yaml'
- name: frontend.address
  $ref: './auto-code.d/common/types/listen-address-any.yaml'
- name: frontend.port
  default: 8000
- name: database.protocol
  $ref: './auto-code.d/common/types/protocols-postgresql.yaml'
- name: database.address
  $ref: './auto-code.d/common/types/listen-address-any.yaml'
- name: database.port
  default: 5432
